---
- name: Install Languages
  hosts: localhost
  tasks:
    - name: Install Volta Node Version Manager
      shell: |
        curl https://get.volta.sh | bash
      args:
        creates: /usr/local/bin/volta

    - name: Install Node
      shell: |
        volta install node
      args:
        creates: /usr/local/bin/node

    - name: Confirm Volta installation
      command: volta --version
      register: volta_version
      changed_when: false

    - name: Confirm Node installation
      command: node --version
      register: node_version
      changed_when: false

    - name: Install Deno
      homebrew:
        name: deno
        state: present

    - name: Confirm Deno installation
      command: deno --version
      register: deno_version
      changed_when: false

    - name: Install Rust
      homebrew:
        name: rust
        state: present

    - name: Confirm Rust installation
      command: rustc --version
      register: rust_version
      changed_when: false

    - name: Output versions
      debug:
        msg:
          - 'Volta version: {{ volta_version.stdout }}'
          - 'Node version: {{ node_version.stdout }}'
          - 'Deno version: {{ deno_version.stdout }}'
          - 'Rust version: {{ rust_version.stdout }}'
